
/*
	chztbby::RebirthGuard/options.h
*/

#ifndef REBIRTHGUARD_OPTION_H
#define REBIRTHGUARD_OPTION_H

#define RG_DISABLE 0x00000000
#define RG_ENABLE 0x00000001
#define RG_ENABLE_LOG 0x00000002	
#define RG_ENABLE_POPUP 0x00000004
#define RG_ENABLE_KILL 0x00000008
#define RG_ENABLE_MEM_FREE 0x00000010

// Set your options.
#define RG_OPT_HIDE_MODULE_LIST (RG_ENABLE)
#define RG_OPT_THREAD_CHECK (RG_ENABLE | RG_ENABLE_LOG | RG_ENABLE_POPUP | RG_ENABLE_KILL)
#define RG_OPT_MEMORY_CHECK (RG_ENABLE | RG_ENABLE_LOG | RG_ENABLE_POPUP | RG_ENABLE_KILL | RG_ENABLE_MEM_FREE)
#define RG_OPT_CRC_CHECK (RG_ENABLE | RG_ENABLE_LOG | RG_ENABLE_POPUP | RG_ENABLE_KILL)
#define RG_OPT_CRC_HIDE_FROM_DEBUGGER (RG_ENABLE)
#define RG_OPT_ANTI_DLL_INJECTION (RG_ENABLE | RG_ENABLE_LOG | RG_ENABLE_POPUP | RG_ENABLE_KILL)
#define RG_OPT_ANTI_DEBUGGING (RG_ENABLE | RG_ENABLE_LOG | RG_ENABLE_POPUP | RG_ENABLE_KILL)
#define RG_OPT_PROCESS_POLICY (RG_ENABLE)
#define	RG_PROCESS_POLICY (PROCESS_CREATION_MITIGATION_POLICY_DEP_ENABLE\
							| PROCESS_CREATION_MITIGATION_POLICY_DEP_ATL_THUNK_ENABLE\
							| PROCESS_CREATION_MITIGATION_POLICY_SEHOP_ENABLE\
							| PROCESS_CREATION_MITIGATION_POLICY_FORCE_RELOCATE_IMAGES_ALWAYS_ON_REQ_RELOCS\
							| PROCESS_CREATION_MITIGATION_POLICY_HEAP_TERMINATE_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY_BOTTOM_UP_ASLR_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY_HIGH_ENTROPY_ASLR_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY_STRICT_HANDLE_CHECKS_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY_EXTENSION_POINT_DISABLE_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY_CONTROL_FLOW_GUARD_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY_FONT_DISABLE_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_REMOTE_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_LOW_LABEL_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_PREFER_SYSTEM32_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY2_STRICT_CONTROL_FLOW_GUARD_ALWAYS_ON)



#endif