
/*
	chztbby::RebirthGuard/options.h
*/

#ifndef REBIRTHGUARD_OPTION_H
#define REBIRTHGUARD_OPTION_H

#define RG_DISABLE			0x00000000
#define RG_ENABLE			0x00000001
#define RG_ENABLE_LOG		0x00000002	
#define RG_ENABLE_POPUP		0x00000004
#define RG_ENABLE_KILL		0x00000008
#define RG_ENABLE_DEALLOC	0x00000010

// Set your options.
//#define RG_OPT_DEBUG_LOG							(RG_DISABLE)

#define RG_OPT_COMPAT_THEMIDA						(RG_DISABLE)
#define RG_OPT_COMPAT_VMPROTECT						(RG_DISABLE)

#define RG_OPT_HIDE_MODULE							(RG_DISABLE)
#define RG_OPT_REBIRTH_SYSTEM_MODULES				(RG_DISABLE & !RG_OPT_COMPAT_VMPROTECT)
#define RG_OPT_REBIRTH_ALL_MODULES					(RG_DISABLE & !RG_OPT_COMPAT_VMPROTECT)
#if __cplusplus >= 201703
#define RG_OPT_SET_PROCESS_POLICY					(RG_DISABLE & !RG_OPT_COMPAT_VMPROTECT & !RG_OPT_COMPAT_THEMIDA)	// EXE only
#endif
#define RG_OPT_ANTI_DLL_INJECTION					(RG_DISABLE | RG_ENABLE_LOG | RG_ENABLE_POPUP | RG_ENABLE_KILL)
#define RG_OPT_ANTI_DEBUGGING						(RG_DISABLE | RG_ENABLE_LOG | RG_ENABLE_POPUP | RG_ENABLE_KILL)
#define RG_OPT_THREAD_CHECK							(RG_DISABLE | RG_ENABLE_LOG | RG_ENABLE_POPUP | RG_ENABLE_KILL)
#define RG_OPT_MEMORY_CHECK							(RG_DISABLE | RG_ENABLE_LOG | RG_ENABLE_POPUP | RG_ENABLE_KILL | RG_ENABLE_DEALLOC)

#define RG_OPT_INTEGRITY_CHECK						(RG_DISABLE) // fix..
#define RG_OPT_INTEGRITY_CHECK_HIDE_FROM_DEBUGGER	(RG_DISABLE) // fix..

#define IS_ENABLED(OPTION) (OPTION & RG_ENABLE)
#if IS_ENABLED(RG_OPT_SET_PROCESS_POLICY)
#define	RG_PROCESS_POLICY (PROCESS_CREATION_MITIGATION_POLICY_DEP_ENABLE\
							| PROCESS_CREATION_MITIGATION_POLICY_DEP_ATL_THUNK_ENABLE\
							| PROCESS_CREATION_MITIGATION_POLICY_SEHOP_ENABLE\
							| PROCESS_CREATION_MITIGATION_POLICY_FORCE_RELOCATE_IMAGES_ALWAYS_ON_REQ_RELOCS\
							| PROCESS_CREATION_MITIGATION_POLICY_HEAP_TERMINATE_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY_BOTTOM_UP_ASLR_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY_HIGH_ENTROPY_ASLR_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY_STRICT_HANDLE_CHECKS_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY_EXTENSION_POINT_DISABLE_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY_CONTROL_FLOW_GUARD_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY_FONT_DISABLE_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_REMOTE_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_LOW_LABEL_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_PREFER_SYSTEM32_ALWAYS_ON\
							| PROCESS_CREATION_MITIGATION_POLICY2_STRICT_CONTROL_FLOW_GUARD_ALWAYS_ON)
#endif

#endif